server:
  port: 8089

spring:
  application:
    name: SERVICE-TNB
  datasource:
    url: jdbc:mysql://localhost/service_tnb?createDatabaseIfNotExist=true&useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    username: root
    password:
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    hibernate:
      ddl-auto: update

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

# Additional properties
main:
  allow-bean-definition-overriding: true
