server:
  port: 8888

spring:

  main:
    web-application-type: reactive
  application:
    name: gateway
  cloud:
      gateway:
        globalcors:
          cors-configurations:
            '[/**]':
              allowedOrigins:
                - "http://localhost:4200/"
              allowedHeaders: "*"
              allowedMethods:
                - "GET"
                - "POST"
                - "OPTIONS"
                - "DELETE"
                - "PUT"
              allowCredentials: true


eureka:
  instance:
    hostname: localhost
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
